service: slackbot

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs6.10
  environment: "${file(secrets.json)}"

package:
  exclude:
    - secrets.json
    - types.ts

functions:
  slashCommand:
    handler: handler.slashCommand
    events:
      - http:
          path: slashCommand
          method: post
  cronCommand:
    handler: handler.cronCommand
    events:
      - schedule: cron(0 8 ? * MON *)